### ISSUE TITLE
Module 'setup' not found

### ISSUE THREAD

**Issue by nina124** [hhexiy/opponent#1]
Hi,
Thank you for sharing the code, I just run it, and get an error: 
`module 'setup' not found:No LuaRocks module found for setup`

I am new to torch. So I cannot figure out whether I did not install some package/part in torch for this _setup module_ or the code just missed this part? And, as to the function `env_setup()`, I cannot find its definition in the code.
Could you please give me some hint on solving this? 

By the way, I found the argument setting in makefile is still about `run_qb`, If I want to `run_soccer`, which part of the arguments should I change?

Sorry to be a bother. Any reply would be really appreciated.

**Comment by hhexiy** [comment]
Sorry! Just added setpu.lua. You should be able to find evn_setup there.
run_qn and run_soccer both use agent_params, you can change it there or overwrite them when calling make.

**Comment by nina124** [comment]
Thank you for reply!
Just another problem: `No LuaRocks module found for model.MultiHot`
Also, in `setup.lua`, it requires _model.MultiHot, model.OneHot, Model.MaskedLookupTable_. None of these modules are in the _model_ folder.
To run_soccer, besides changing _agent="QBNeuralQLearner"_ to _agent="SoccerNeuralQLearner"_,  do i need to do other modifications? And what does the argument _nework_ mean? Current it is blank character.

**Comment by hhexiy** [comment]
Oh, those are not used any more.. I've removed them in setup.lua.
network is used to load saved model, you can look at it here: https://github.com/hhexiy/opponent/blob/e97a54f13cdabd86306bd866d6575d9ae9d30413/dqn/QBNeuralQLearner.lua#L65

**Comment by nina124** [comment]
You are so kind for answering so quickly and giving detailed explanation! 
After removing these three lines, it gives `soccer_framework.lua: No such file or directory`.

**Comment by hhexiy** [comment]
Hi, really sorry about the missing files. It's added now.

**Comment by nina124** [comment]
It works now. Thank you so much!
Last, what is the difference between _QBNeuralQLearner.lua_ and _QBONeuralQLearner.lua_, likewise _SoccerNeuralQLearner.lua_ and _SoccerONeuralQLearner.lua_ ?

**Comment by hhexiy** [comment]
O means with opponent.

**Comment by nina124** [comment]
Thanks for all the reply. I will dive into the code.
